name: dio_bloc_rxdart_movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  page_indicator: ^0.4.1
  rxdart: ^0.27.7
  sliver_fab: ^1.0.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
